Feature - Naming attribute on type creation, Delete button for attributes
bptlab/rembrandt-frontend pull request #45
Opened 2019-06-18 14:50 UTC by friedow

This resolves #41.

2019-06-20 10:18 UTC, Munin33 requested changes

2019-06-20 10:18 UTC, Munin33 commented on src/views/CreateType.vue
> +    this.setEponymousAttribute();
when saving a attribute after disabling the Eponymous-toggle it is still classified as "naming"

2019-06-20 10:18 UTC, Munin33 commented on src/utils/Utils.ts
> +      if (resourceInstance.resourceType.eponymousAttribute) {
this "if" is exactly the same as above, so one should be sufficient?

2019-06-25 08:27 UTC, MaximilianV approved these changes

2019-06-25 09:00 UTC, Munin33 approved these changes

2019-06-25 09:04 UTC, merged