Feature/29 edit instances
bptlab/rembrandt-frontend pull request #48
Opened 2019-06-25 13:55 UTC by Munin33

2019-06-25 15:00 UTC, friedow requested changes

2019-06-25 15:00 UTC, friedow commented on src/router.ts
> +    {
Move this route above the 'resource' route to avoid route matching conflicts.

2019-06-25 15:00 UTC, friedow commented on src/views/EditInstance.vue
> +    <ViewHeader title="Choose new attribute values for the instance" :backLink="{ link: `/resources/${this.instanceId}` }"/>
Please use a named route objects for navigation. (reference code inside `saveResourceInstance`).

2019-06-25 15:00 UTC, friedow commented on src/views/EditInstance.vue
> +        this.$router.push({ name: 'resource', params: { id: this.updatedResourceInstance.id } });
👍

2019-06-25 15:59 UTC, Munin33 commented on src/router.ts
> +    {
done

2019-06-25 16:00 UTC, Munin33 commented on src/views/EditInstance.vue
> +    <ViewHeader title="Choose new attribute values for the instance" :backLink="{ link: `/resources/${this.instanceId}` }"/>
Ah, I overlooked this one, thanks!

2019-06-27 07:40 UTC, friedow approved these changes

2019-06-27 07:41 UTC, merged